"""
Exporter Module
Handles exporting recordings to Word documents
"""

import logging
import os
from datetime import datetime
from typing import List, Dict

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


class WordExporter:
    """Exports note recordings to Word documents"""
    
    @staticmethod
    def export_to_word(notes: List[Dict], filepath: str, duration: float) -> bool:
        """
        Export recording to Word document.
        
        Args:
            notes: List of note dictionaries
            filepath: Path to save the .docx file
            duration: Total recording duration in seconds
            
        Returns:
            True if successful, False otherwise
        """
        logging.info("export_to_word called for %s", filepath)
        try:
            # Ensure the directory exists
            directory = os.path.dirname(filepath)
            if directory and not os.path.exists(directory):
                logging.info("Creating directory %s", directory)
                os.makedirs(directory)
            
            # Create document
            doc = Document()
            logging.info("Document object created")
            
            # Add title
            title = doc.add_heading('NoteFlow Recording', 0)
            title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            
            # Add recording metadata
            doc.add_paragraph()
            metadata = doc.add_paragraph()
            metadata.add_run('Recording Date: ').bold = True
            metadata.add_run(datetime.now().strftime('%B %d, %Y at %I:%M %p'))
            
            duration_para = doc.add_paragraph()
            duration_para.add_run('Total Duration: ').bold = True
            duration_para.add_run(f"{duration:.2f} seconds")
            
            note_count = doc.add_paragraph()
            note_count.add_run('Total Notes: ').bold = True
            note_count.add_run(str(len(notes)))
            
            # Add spacing
            doc.add_paragraph()
            
            # Add notes sequence heading
            doc.add_heading('Note Sequence', 2)
            
            if notes:
                # Create note sequence
                sequence = " → ".join([note['note_name'] for note in notes])
                sequence_para = doc.add_paragraph(sequence)
                sequence_para.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
                
                # Add spacing
                doc.add_paragraph()
                
                # Add detailed notes heading
                doc.add_heading('Detailed Note List', 2)
                
                # Add table with note details
                table = doc.add_table(rows=1, cols=4)
                table.style = 'Light Grid Accent 1'
                
                # Header row
                header_cells = table.rows[0].cells
                header_cells[0].text = '#'
                header_cells[1].text = 'Note'
                header_cells[2].text = 'Time (s)'
                header_cells[3].text = 'Velocity'
                
                # Make header bold
                for cell in header_cells:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.bold = True
                
                # Add note rows
                for i, note in enumerate(notes, 1):
                    row_cells = table.add_row().cells
                    row_cells[0].text = str(i)
                    row_cells[1].text = note['note_name']
                    row_cells[2].text = f"{note['relative_time']:.2f}"
                    row_cells[3].text = str(note['velocity'])
            else:
                doc.add_paragraph('No notes recorded')
            
            # Add footer
            doc.add_paragraph()
            footer = doc.add_paragraph()
            footer.add_run('\n\nGenerated by NoteFlow - MIDI Note Recorder').italic = True
            footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            
            # Save document
            doc.save(filepath)
            logging.info("Document saved to %s", filepath)
            return True
            
        except PermissionError:
            logging.exception("Permission denied writing %s", filepath)
            return False
        except Exception:
            logging.exception("Error exporting to Word for %s", filepath)
            return False
